language: go

go:
  - 1.7

node_js:
  - "0.12"

julia:
  - 0.5

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Frieda Rong"
        - GIT_EMAIL="adeirff@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_372990b028ab_key -iv $encrypted_372990b028ab_iv
  -in travis_key.enc -out travis_key -d

install:
    - go get -v github.com/spf13/hugo
    - npm install --save-dev grunt string toml
    - npm install -g grunt-cli

script:
    - ./rebuild_schedule.jl
    - grunt lunr-index
    - hugo

after_success:
    - ./deploy.sh
